### ISSUE TITLE
Support more than 10 socket connections 

### ISSUE THREAD

**Issue by minchopm** [gondar00/yjs-websocket-server-with-nestjs#2]
I am trying to add setMaxListeners(100) but it is always throwing an error:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners. Use emitter.setMaxListeners() to increase limit

**Comment by gondar00** [comment]
Hey @minchopm, this [bug](https://github.com/gondar00/yjs-websocket-server-with-nestjs/commit/17b1236788b4f1d62c03d9c382dc16c4c88942c7) has been fixed on latest master.
